apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: serverhorror.httphostname
spec:
    replicas: 1
    template:
        metadata:
            labels:
                run: serverhorror-httpHostname
        spec:
            containers:
                - name: serverhorror-httphostname
                  image: serverhorror/httphostname
                  ports:
                  - containerPort: 8080
