apiVersion: v1
kind: Service
metadata:
    name: serverhorror-httphostname
    labels:
        run: serverhorror-httpHostname
spec:
    type: NodePort
    ports:
    - port: 8080
      targetPort: 8081
      protocol: TCP
    selector:
        run: serverhorror-httpHostname